apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    com.myapp.description: vault server
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vault
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vault
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        com.myapp.description: vault server
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/vault: "true"
        io.kompose.service: vault
    spec:
      containers:
      - command:
        - vault
        - server
        - -config=/config/consul-config.json
        env:
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        image: vault:latest
        imagePullPolicy: ""
        name: vault
        ports:
        - containerPort: 8200
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - mountPath: /config
          name: vault-claim0
        - mountPath: /policies
          name: vault-claim1
        - mountPath: /vault/logs
          name: vault-logs
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: vault-claim0
        persistentVolumeClaim:
          claimName: vault-claim0
      - name: vault-claim1
        persistentVolumeClaim:
          claimName: vault-claim1
      - name: vault-logs
        persistentVolumeClaim:
          claimName: vault-logs
status: {}
